name: fooddelivery_fe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  awesome_snackbar_content: ^0.1.3
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.5
  geolocator: ^8.0.1
  get: ^4.6.5
  intl: ^0.18.1
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.3
  logger: ^1.4.0
  lottie: ^2.7.0
  http: ^0.13.6
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  firebase_storage: ^11.1.0
  shared_preferences: ^2.1.0
  flutter_slidable: ^3.0.1
  flutter_screenutil: ^5.9.0

  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  easy_localization: ^3.0.3
  # cached_network_image: ^3.2.3
  mapbox_polyline_points: ^0.0.5
  mapbox_maps_flutter: ^0.4.3

  flutter_polyline_points: ^1.0.0
  custom_map_markers: ^0.0.2+1
  cupertino_icons: ^1.0.6
  polyline_do: ^0.1.0
  dio: ^5.1.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.12.1
  webview_flutter_platform_interface: ^2.7.0
  webview_flutter_wkwebview: ^3.9.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
