name: fooddelivery_fe
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  get: ^4.6.5
  intl: ^0.18.1
  http: ^0.13.6
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.3
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  otp_pin_field: ^1.2.2
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.5.0
  custom_map_markers: ^0.0.2+1
  image_picker: ^1.0.4
  flutter_timezone: ^1.0.8
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/icons/
    - assets/translations/
    - assets/img/categories/
